//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public enum StructureUnitType
	{
		Settlement,
		TownHall,
		CityHall,
		Capitol,
		Exporter,
		Factory,
		Market,
		Contractor,
		LabourCamp,
		Propaganda,
		Airport,
		Barracks,
		TankDepot
	}

	public class StructureUnit
	{
		public StructureUnit ()
		{
		}
	}
}

